### ISSUE TITLE
Add custom attribute to UILabel

### ISSUE THREAD

**Issue by jbender** [motion-kit/motion-kit#101]
I may be missing something obvious, but I'm unable to add custom attributes to a UILabel that would allow it to break into multiple lines. Normally after making the label I'd just call the following (Swift):

    textLabel.lineBreakMode = NSLineBreakMode.ByWordWrapping
    textLabel.numberOfLines = 0

I assume that I'd be doing this in the style function, but am unsure what the "magic words" are for custom attributes that don't have their own convenience methods.

    def layout
      add UILabel, :custom_label
    end

    def custom_label_style
      text "Some really long string that I want to break into a couple lines"
      # line_break_mode NSLineBreakModeByWordWrapping
      # number_of_lines 0
    end

**Comment by colinta** [comment]
The code you have looks right to me - no need for convenience methods here.  Is there an error or something?  What's the expected vs observed behavior?

**Comment by jbender** [comment]
Yeah, I'm getting the following error:

    Terminating app due to uncaught exception 'NameError', reason: 'home_layout.rb:13:in `really_long_label_style': uninitialized constant HomeLayout::NSLineBreakModeByWordWrapping (NameError)

------

    class HomeLayout < MK::Layout
      
      def layout
        root :main do
          add UILabel, :really_long_label
        end
      end

      def really_long_label_style
        text "A really long string that needs to be broken into a couple lines"
        line_break_mode NSLineBreakModeByWordWrapping
        number_of_lines 0
        frame [['25%', '25%'], ['25%', '50%']]
      end

      def main_style
        background_color "#1E2129".uicolor
      end

    end

**Comment by jbender** [comment]
I also tried with just `ByWordWrapping`, which resulted in a similar `NameError`

**Comment by jbender** [comment]
Ah, I was following a bad SO post, should be:

    def label_has_word_wrapping
      line_break_mode NSLineBreakByWordWrapping
      number_of_lines 0
    end

**Comment by colinta** [comment]
Classic :smile: HTH!
