### ISSUE TITLE
Question/Request: Resizing parent view to subview sizes

### ISSUE THREAD

**Issue by holgersindbaek** [motion-kit/motion-kit#105]
I've tried out constraints and it's terrible to work with. I would love the ability to make a parent view resize itself (heigh and/or width) to make itself as big as the subviews it contains.

For example:

      add UILabel, :title_label
      add UIView, :divider_view
      add UIView, :info_container do
        add UIImageView, :used_image
        add UILabel, :used_label
        add UIImageView, :color_image
        add UILabel, :color_label
        add UIImageView, :ruler_image
        add UILabel, :ruler_label
      end

      add ProfileView, :profile_view

:info_container should resize its own height to be as big as all its subviews, so I can position the :profile_view below it like this - below(:info_container).

Does this make sense? Am I going about it in the wrong way?

**Comment by jamonholmgren** [comment]
Hey @holgersindbaek,

Constraints are sometimes a big pain, for sure.

I'd do something like this:

```ruby
  add UILabel, :title_label
  add UIView, :divider_view
  add UIView, :info_container do
    add UIImageView, :used_image
    add UILabel, :used_label
    add UIImageView, :color_image
    add UILabel, :color_label
    add UIImageView, :ruler_image
    add UILabel, :ruler_label
  end

  add ProfileView, :profile_view


# ...

def info_container_style
  constraints do
    min_bottom.equals(:used_image)
    min_bottom.equals(:used_label)
    min_bottom.equals(:color_image)
    min_bottom.equals(:color_label)
    min_bottom.equals(:ruler_image)
    min_bottom.equals(:ruler_label)
  end
end
```

I need to go through and exhaustively document all the possible constraint options. This is [listed in the docs](https://github.com/motion-kit/motion-kit/blob/master/READMORE.md#autolayout) but we need more examples.

**Comment by holgersindbaek** [comment]
Thanks for the answer @jamonholmgren. I've already implemented the whole view with constraints, but it seems so immensely clumsy. It takes a long time to make things right and you have to write MANY lines of codes to make the constraints work.

I've re-written stuff things, so the views that have a superview, that needs to expands, calls - resize_superview_to_fit_height - which calls a method on the superview that goes through it's subviews and resizes accordingly. It seems to be working quite well, but it's not perfect.

Much simpler and much less code than constraints though. Any change of implementing something like this in MotionKit? Like an option on a superview called - automatic_resize - that will resize the view, each time a subview is added?

**Comment by matthewsinclair** [comment]
I have a love/hate relationship with these things. When it works, it's great, but when it doesn't, you end up in the seventh level of [hell](https://github.com/motion-kit/motion-kit/issues/103). :)

One thing that I have thought about from time to time is if we could use the auto layout text strings in the constraint block?

For example:

```
  def my_view_style
    constraints do
      horizontal "|-(my_other_view)-|"
      vertical "|-(my_top_view)-(my_other_view)-(my_bottom_view)-|
      # etc 
    end 
  end 
```

Excuse the rough syntax, but I think you get my point. The `my_other_view` etc items in the auto layout strings would represent the symbols used to name the views added in the `layout` method. I sometimes think that having access to that syntax would make more complex layouts easier to work with.

Anyway, I know this stuff is really hard, so I appreciate the effort that goes into it all. 

Thanks,
M@

**Comment by jamonholmgren** [comment]
Interestingly, @holgersindbaek, our latest app uses constraints exclusively and the code is really simple. Here's an example of our most complex screen, which is a detail screen (think like Instagram's individual video detail screen): https://gist.github.com/jamonholmgren/dea5986742037bc3a64e

Maybe we just had a simpler use case, but overall it was pretty pleasant. I do agree that it can be really convoluted sometimes. For example, we needed to implement a list of tags that were left-floated and wrapped down a line when there were too many. We ended up just making a web view for that. Don't tell anyone. ;)

**Comment by holgersindbaek** [comment]
Still seems very "complicated"... or at least clumsy. This is my layout file currently - https://gist.github.com/holgersindbaek/91ab2395699ac49d1ab4. The thing that strikes me with constraints, is that you have to basically write 3-4 lines of code for each view, plus the constraints do and end line. Which makes for a LOT of lines and difficulty getting a quick overview of things.

**Comment by jamonholmgren** [comment]
@holgersindbaek Hm, I guess my expectations are a bit different then. :) Certainly frame-based layouts will be fewer lines in most cases, but the tradeoff is worth it, at least to me.

To be entirely honest, if you're not using constraints (plug your ears @colinta) I wouldn't use MotionKit at all. Your stylesheets should port over nicely to @twerth's [RMQ stylesheets](http://rubymotionquery.com/documentation/#cat-10).

**Comment by twerth** [comment]
^ :-)

**Comment by colinta** [comment]
Having the parent view size according to it's child views can be done two ways:

1. Use constraints
2. Use `layoutSubviews` and calculate the size of the *current* view based on the child views.

I don't think you can accomplish this goal using only frames and resizing masks.
