### ISSUE TITLE
How to set custom background color for UIButton for different states?

### ISSUE THREAD

**Issue by cbetta** [motion-kit/motion-kit#107]
Anyone got a clue?

**Comment by colinta** [comment]
The easiest way is really dumb, but create a 1x1 pixel image of the colors you want, and assign that to `backgroundImage(forState:)`.  Using SugarCube it's easy to generate images at runtime:

```ruby
white_bg = UIImage.canvas([1,1]) do |context|
  :white.uicolor.set
  CGContextAddRect(context, [[0, 0], [1, 1]])
  CGContextDrawPath(context, KCGPathFill)
end

button.setBackgroundImage(white_bg, forState: :normal.uicontrolstate)
```

**Comment by colinta** [comment]
Closing, since this isn't a MotionKit issue. <http://stackoverflow.com/questions/4049103/iphone-how-to-set-backgroundcolor-of-uibutton-with-buttontype-uibuttontypecust>
