### ISSUE TITLE
Can't launch Chatty iOS sample

### ISSUE THREAD

**Issue by lizvdk** [motion-kit/motion-kit#110]
There seems to be an issue with Firebase.

Running the default rake task gets me this error:
Undefined symbols for architecture i386:
  "_fwrite$UNIX2003", referenced from:
      leveldb::(anonymous namespace)::PosixEnv::~PosixEnv() in Firebase(env_posix.o)
      leveldb::(anonymous namespace)::PosixEnv::~PosixEnv() in Firebase(env_posix.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

https://github.com/motion-kit/motion-kit/tree/master/samples/ios/Chatty

**Comment by colinta** [comment]
Very strange, other than having an error because I didn't include `rake` in the `Gemfile`, it compiled and ran in the sim.

Try a quick `rake clean:all`, I'll check on my rubymotion/xcode versions.

**Comment by colinta** [comment]
```
> motion --version
3.8
> xcodebuild -version
Xcode 6.3
Build version 6D570
```

**Comment by colinta** [comment]
Very cryptic errors there.  Can you can compile other RubyMotion projects?

**Comment by colinta** [comment]
I'd love to help, but you seem to have disappeared...
