### ISSUE TITLE
tool bar with motion-kit and promotion not in correct way

### ISSUE THREAD

**Issue by poc7667** [motion-kit/motion-kit#113]
I added `will_appear` to show the `tool bar` but it seems not working,

If I added the  `will_appear` in the  `reservoirs_view (reservoirs_screen.rb)`, 

The toolbar will pin to on a strange position, I expect it will be fixed at the bottom of window.

![](https://i.imgur.com/jQnR4iw.png)

# home_layout.rb

	class HomeLayout < MK::Layout
	  view :reservoirs_view
	  def layout
	    root :main do
	      add reservoirs_view, :reservoirs
	    end
	  end

	  def main_style
	    background_color "#F9F9F9".uicolor
	  end

	  def will_appear
	    view.setBackgroundColor UIColor.blackColor
	    view.addSubview(@toolbar = UIToolbar.new)
	    table_height = tableView.bounds.size.height
	    table_width = tableView.bounds.size.width
	    print("height"+table_height.to_s)
	    @toolbar.frame = CGRectMake(0, table_height, table_width, 100)
	    @toolbar.setItems([
	      UIBarButtonItem.alloc.initWithTitle(
	        "Hello",
	        style: UIBarButtonItemStylePlain,
	        target: self,
	        action: 'hello_pressed:'
	      ),
	      UIBarButtonItem.alloc.initWithBarButtonSystemItem(
	        UIBarButtonSystemItemFlexibleSpace,
	        target: nil,
	        action: nil
	      ),
	      UIBarButtonItem.alloc.initWithBarButtonSystemItem(
	        UIBarButtonSystemItemAction,
	        target: self,
	        action: 'hello_pressed:'
	      )
	    ])    
	    
	  end

**Comment by colinta** [comment]
Using either AutoLayout, or setting the `frame` and `autoresizingMask`, you should be able to add the toolbar at *layout*-time, instead of at *will_appear*.  Keep in mind, too, that `viewWillAppear` gets called many times, so you'll have a weird situation where your view could easily end up with multiple toolbars.

It's also unclear where `resevoirs_view` comes from.  I guess that is being handed to the layout?

In the `main_style` method, you can add the toolbar:

```ruby
def main_style
  add UIToolbar do
    frame from_bottom(height: 100, width: '100%')
    autoresizing_mask :fill_bottom

    items [
      UIBarButtonItem.alloc.initWithTitle(
        "Hello",
        style: UIBarButtonItemStylePlain,
        target: self,
        action: 'hello_pressed:'
      ),
      UIBarButtonItem.alloc.initWithBarButtonSystemItem(
        UIBarButtonSystemItemFlexibleSpace,
        target: nil,
        action: nil
      ),
      UIBarButtonItem.alloc.initWithBarButtonSystemItem(
        UIBarButtonSystemItemAction,
        target: self,
        action: 'hello_pressed:'
      )
    ]
end
```

**Comment by colinta** [comment]
You could also create a dedicated `toolbar_style` method (I would!)

```ruby
  def layout
    root :main do
      add reservoirs_view, :reservoirs
      add UIToolbar, :toolbar
    end
  end
```

**Comment by poc7667** [comment]
Hi Thanks for your anwser,but sadly your solution not works for me, 

It didn't show anything.

Maybe its due to I show the whole view with `reservoirs_screen.rb` ?

Here's the [gist](https://gist.github.com/poc7667/5b2b841f2b79801aa836) to show how I include the **tableview**

Should I define a file called `reservoirs_view` ?
I thought I only need to define a corresponding file `reservoirs_screen.rb`

I just followed this tutorial [lnk](http://jamonholmgren.com/getting-started-with-motionkit-and-promotion/) to create my app.

**Comment by colinta** [comment]
What is the goal with the `will_appear` method?  Where does the `resevoir_view` come from?  Is it assigned to your layout from somewhere?

Your `hello_pressed` handler should emit an application event (if you include `motion-kit-events`), it doesn't have access to the `navigationController`

```ruby
  def hello_pressed(sender)
    trigger(:show_resevoirs_screen)
  end
```

When you say "it didn't show anything", I'm not sure what you mean.  Was the screen black?  No toolbar?

**Comment by colinta** [comment]
Here's a quick example of creating a `UIToolbar` and placing it at the bottom: <https://gist.github.com/colinta/8889db978032a9417884>

**Comment by poc7667** [comment]
I'm really appreciate your help,  thank you so much :)
"it didn't show anything", means I didn't see the toolbar. But I found the root cause is I use the MK:layout and promotion incorrectly, I need to read more documentation to  realize how to use it correctly. thanks

**Comment by colinta** [comment]
Good luck! :smiley:

**Comment by theCrab** [comment]
@colinta I think it would have been nice to solve this question. I have a similar problem using Promotion and MK.

I think the toolbar in this case is being placed behind the view.

In **ProMotion**. The `on_load` creates a view unless you create it yourself. So in my case a `MKMapView` is created.

```rb
def on_load
  # an implicit UIView/MKMapView is created here unless you define one manually
  # alias is view or map
end
```

In **MotionKit:** 
[Here is my code](https://gist.github.com/theCrab/5f57a4662641e2e54f7a4c1ab1be61e9) and in the image below I cannot touch the map view because there is another view from `MapLayout#layout` on top of it that contains the black screens. I want the map to be reloaded every time the map appears.

How can I fix this?

![simulator screen shot 22 nov 2016 10 16 12](https://cloud.githubusercontent.com/assets/3485249/20583199/286dc9e4-b1e0-11e6-9d35-b23ce4feed38.png)

**Comment by theCrab** [comment]
I think the problem with @poc7667 question is that there is a hidden toolbar already. All you need to do is make it visible then add your items to it.

```rb
  def will_appear
    # ...
    navigationController.toolbarHidden = false
  end

  def on_appear
    items = %w(One Two Three)
    @uisc = UISegmentedControl.alloc.initWithItems(items).tap do |usc|
      usc.addTarget(self, action: "segment_changed:", forControlEvents:UIControlEventValueChanged)
      usc.momentary = false
      usc.segmentedControlStyle = UISegmentedControlStyleBar
      usc.selectedSegmentIndex = 0
    end
    sgc = UIBarButtonItem.alloc.initWithCustomView(@uisc)

    set_toolbar_items(
      [
        { system_item: :flexible_space },
        sgc,
        { system_item: :flexible_space }
      ],
      animated: true
    )
  end
```
