### ISSUE TITLE
Creating view controller with a lot of views is really slow

### ISSUE THREAD

**Issue by holgersindbaek** [motion-kit/motion-kit#114]
I'm trying to create a UIViewController with a lot of subview views and it seems like creating the views take a long time. 

It takes around 0.5-1 second for my UIViewController to be rendered, so I can display it on my screen.

This is is some of the views that gets added to the UIViewController. There's about twice as many views that gets added:

    def layout
      root :root do
        add MLPJVFloatLabeledTextField, :title_label
        add UIView, :title_label_border
        add UIView, :info_container do
          add UIImageView, :used_image
          add AKPickerView, :used_label
          add UIImageView, :color_image
          add FloatLabel, :color_label
          add UIImageView, :ruler_image
          add AKPickerView, :ruler_label
        end
        add UIView, :list_container do
          add UIView, :box_container do
            add UILabel, :box_label
            add UIView, :box_image_container { add UIImageView, :box_image_view }
            add UIView, :divider_view
          end
          add UIView, :receipt_container do
            add UILabel, :receipt_label
            add UIView, :receipt_image_container { add UIImageView, :receipt_image_view }
            add UIView, :divider_view
          end
          add UIView, :nickname_container do
            add UILabel, :nickname_static_label
            add FloatLabel, :nickname_label
            add UIView, :divider_view
          end
          add UIView, :style_container do
            add UILabel, :style_static_label
            add FloatLabel, :style_label
            add UIView, :divider_view
          end
          add UIView, :release_container do
            add UILabel, :release_static_label
            add FloatLabel, :release_label
            add UIView, :divider_view
          end
          add UIView, :box_dimensions_container do
            add UILabel, :box_dimensions_label
            add FloatLabel, :box_length_label
            add FloatLabel, :box_width_label
            add FloatLabel, :box_height_label
            add UIView, :divider_view
          end
          add UIView, :box_weight_container do
            add UILabel, :box_weight_static_label
            add FloatLabel, :box_weight_label
          end
        end
        add UIView, :price_container do
          add TSJVFloatLabeledTextField, :price_label
        end
        add UIView, :note_container do
          add JVFloatLabeledTextView, :note_text_view
        end
      end
    end

I've tracked what about creating the UIViewController takes a long time and it seems to be the creation and adding the subviews to the controllers view, that each take 5-10 milliseconds. This sums up to a long time, when you have a lot of views.

Is this normal? Is it a MotionKit thing or and Obj-C thing? Are there any ways of going around this?

**Comment by colinta** [comment]
Do all these methods also have `_style` methods associated with them?  Even then, that's crazy slow.

**Comment by holgersindbaek** [comment]
They most certainly do and I'm placing them in relation to each other. Not sure why it's so slow, but you wouldn't say that is normal?



—

**Comment by colinta** [comment]
I feel like I've done some pretty crazy views, but I've never seem them take *this* long.  I don't know how to get this faster. :-/

**Comment by holgersindbaek** [comment]
Hmmm... might be something I'm doing then. I'll look more into it later.

I'll be closing the issue for now. Might get back with an update on what I was doing.
