### ISSUE TITLE
Support for designated (non-simple) initializers on OS X 

### ISSUE THREAD

**Issue by astechishin** [motion-kit/motion-kit#115]
In lib/motion-kit/helpers/tree_layout.rb the protected method initialize_element has the comment:
     # This will need to be smarter going
    # forward as `new` isn't always the designated initializer

I am hoping that time is now. 

To create a NSMatrix control on an OS X view the designated initializer is initWithFrame:mode:cellClass:numberOfRows:numberOfColumns: 

Unfortunately once an NSMatrix view is created, there is no setter for the number of columns or rows, you need to call addRow and addColumn multiple times.

Allowing the elem parameter to be either a Class or an instance would allow the add method in the to work like:

add NSMatrix.alloc.initWithFrame([[0,0],[0,0]], mode: NSRadioModeMatrix, cellClass: thing, numberOfRows: 4, numberOfColumns: 3), :my_radio_grid

**Comment by colinta** [comment]
Actually, the `add` method already accepts an instnace!  It's only when you use the shorthand:

```add NSMatrix, :my_radio_grid```

that `new` is called on the class.  You can pass in an instance instead, like you are doing here.

**Comment by astechishin** [comment]
Cool, works perfectly, sorry to have caused you any trouble Colin. Thanks to you Jamon for such a great gem.

**Comment by jamonholmgren** [comment]
:+1: Glad you're finding it useful!

**Comment by jamonholmgren** [comment]
(I assume you meant "you and Jamon" -- Colin is the primary dev on this!)

**Comment by astechishin** [comment]
Yeah, should always take one last read before hitting submit. Thanks to both of you

And it is extremely useful, I can't imagine working without it
