### ISSUE TITLE
TVOS is not supported

### ISSUE THREAD

**Issue by egze** [motion-kit/motion-kit#125]
When I run rake, I get:

`Sorry, the platform :tvos (aka ) is not supported by MotionKit`

How hard would it be to add support? Maybe I can try to do it myself, if anyone points me to the right direction.

**Comment by colinta** [comment]
It might be *really* easy, since tvOS uses UIKit.  This error message comes from <https://github.com/motion-kit/motion-kit/blob/master/lib/motion-kit.rb#L20>.  If you do a check there for `:tvos`, you can set the platform_name to 'ios' and run with it, see if that "just works"!

I'll be very interested to hear how that goes!  Looking forward to a PR, too! ;-)

**Comment by egze** [comment]
It does compile with this hack, that's already good! :) But a proper PR might take a while. When I run the specs, it errors with

```
should style :gradient layer
Can't find pointer description for type `{CGColor=}'
```
Who knows what else broke. I sadly don't have much time now to dive deep into it.

**Comment by egze** [comment]
@colinta Can you take a look please and give some hints what to do?

https://github.com/egze/motion-kit/pull/1

**Comment by colinta** [comment]
I guess tvos doesn’t support CALayer modifications?

The only thing to do, then, is to remove those files (anything that references CALAyer code) from `app.spec_files` and `app.files` if the platform is :tvos (inside the Rakefile)

**Comment by egze** [comment]
I don't think that CALayer modifications are not supported.

Is this piece of code supposed to work? `UIColor.whiteColor.CGColor`

I'm getting 
```
Can't find pointer description for type `{CGColor=}'
```
in the console for iOS project and for TvOS.

SDK version is 9.1

**Comment by colinta** [comment]
```
(main)> UIColor.whiteColor.CGColor
=> #<__NSCFType:0x11174f830>
```

Weird!

**Comment by egze** [comment]
What SDK and Rubymotion versions?

Can you please also run the specs from my branch? Maybe it's all green from you.

**Comment by colinta** [comment]
Will do!

**Comment by colinta** [comment]
iOS: ```623 specifications (2755 requirements), 0 failures, 0 errors```
OSX: ```620 specifications (2701 requirements), 0 failures, 0 errors```
tvOS: ```should style :gradient layer
Can't find pointer description for type `{CGColor=}'```

**Comment by colinta** [comment]
First, I removed `spec/tvos/calayer_spec.rb`.  Then:

```diff
diff --git a/spec/tvos/frame_helper_spec.rb b/spec/tvos/frame_helper_spec.rb
index 02c9ecf..b2295a4 100644
--- a/spec/tvos/frame_helper_spec.rb
+++ b/spec/tvos/frame_helper_spec.rb
@@ -1,9 +1,8 @@
 describe 'Frame helpers' do
-  tests UIViewController

   before do
     @layout = TestEmptyLayout.new
-    top_view = @controller.view
+    top_view = UIView.new
     @layout.root = top_view

     @view_size = CGSize.new(8, 10)
```

**Comment by colinta** [comment]
I'm this far along:

```
Layouts automatically apply styles

should call all style methods
...
should apply all styles
.....
Autoresize helpers
.............................
MotionKit.calculate
......
should return percents with offset
......
should return point with :origin
..........
should return size with :size
..............
should return frame with :frame
............
MotionKit::Calculator
..........
Child Layouts
.......
Calling reapply! on parent layout
.....
Constraints - activate/deactivate helpers
.
Constraints - attribute lookup
.....
Constraints - axis lookup
..
Constraints - Center helpers
........................
Constraints - placeholder helpers
...
Constraints - priority lookup
...
Constraints - relationship lookup
.....
Constraints - Relative corners helpers
........
Constraints - Relative location helpers
....
Constraints - Size helpers
..
Constraints - Simple helpers

`x/left` support
..............................
`center_x` support
...............
`right` support
...............
`y/top` support
..................
`center_y` support
...............
`bottom` support
...............
`width` support
............
`height` support
............
`leading` support
............
`trailing` support
............
`baseline` support
............
Constraints - Size helpers
.............................
Constraints - view_lookup method
...
Create Layout
........
Custom Layout
.
Custom Root Layouts
.........
TestDeferredLayout

from layout
...
from create_view
...
from error_no_context
.
from nested_blocks
....
from apply_layouts
....
Device helpers
..
Frame helpers
.................................................................................................
TestLayerHelpers
Can't find pointer
```

**Comment by colinta** [comment]
```
	deleted:    app/tvos/spec/test_calayer_layout.rb
	deleted:    app/tvos/spec/test_layer_layout.rb
	deleted:    spec/tvos/calayer_spec.rb
	modified:   spec/tvos/frame_helper_spec.rb
	deleted:    spec/tvos/layer_layout_spec.rb

615 specifications (2745 requirements), 0 failures, 0 errors
```

Progress!

**Comment by colinta** [comment]
I'm getting a "no `exit` method" error, not sure what to do about that.

**Comment by egze** [comment]
Did you also delete `tvos/calayer_spec.rb`? There are failing tests there.

`[ERROR: NameError - uninitialized constant TestCALayerLayout] - should set the frame`

**Comment by colinta** [comment]
Yes, anything CALayer related.

**Comment by egze** [comment]
I got a no `exit` as well. I think it's a rubymotion or bacon bug.

**Comment by egze** [comment]
I still think that `CALayer` modification is supported. I compiled a test tvos app where I did

```ruby
layer do
  corner_radius 7.0
  shadow_opacity 0.9
  shadow_radius 2.0
  shadow_offset [0, 0]
end
```

And it worked. But if I added `shadow_color UIColor.whiteColor.CGColor` in there - crash

**Comment by colinta** [comment]
Ahh gotcha - so just CGColor?  hmm, but it *is* in the documentation.  Odd, I would chalk it up to a possible RM compiler error.  Looks like the branch *is working*, though, so maybe we just disable the CGColor tests for now, and report the error to HipByte?

**Comment by egze** [comment]
Sounds good. Here? https://github.com/HipByte/RubyMotion/issues

**Comment by egze** [comment]
Btw, since UIColor.whiteColor.CGColor works for you in the console, can you please check if it works in the real app in `layer do` ?

**Comment by egze** [comment]
I'll push a sample tvos app if you want

**Comment by colinta** [comment]
Ah, use `motion support` to file bugs related to the runtime.  HipByte/RubyMotion is only for issues on the Rakefile (and that whole system)

**Comment by colinta** [comment]
And yeah, a tvos sample would be handy - we could port it, and put it in the samples/ folder!

**Comment by egze** [comment]
Do you know if there is a DSL to skip/disable tests? In ruby RSpec there is `skip: true` or `skip do` block.
