### ISSUE TITLE
Best way to hide/show view elements?

### ISSUE THREAD

**Issue by dchersey** [motion-kit/motion-kit#130]
Hi, I'm looking for a clean way to conditionally show view elements with motion-kit.

I tried the following in my layout:

```ruby
def sign_in_style
    title 'Sign In'
    # other button styling stuff
   always do
        hidden=user.signed_in?
   end
end
```
and calling reapply! when the user's signed_in? status has changed. 
However it's not doing anything, even though hidden is a property of a UIView.

Similar code is working to update the text in a label relating to the user's sign in status.

I wound up using RMQ to do this but I'm not happy with the ugliness of the code -- in my screen I made a method:

```ruby
  def hide_show_buttons
    if user.signed_in?
      rmq(@layout.sign_in).hide
      rmq(@layout.sign_up).hide
      rmq(@layout.sign_out).show
    else
      rmq(@layout.sign_in).show
      rmq(@layout.sign_up).show
      rmq(@layout.sign_out).hide
    end
  end
end
```
Using a motion_kit helper would be cleaner and remove the code to the layout.  Any suggestions?

**Comment by colinta** [comment]
Instead of assigning to `hidden` (which, in this case, is just a local variable), you can just *call* `hidden`.

    hidden(user.signed_in?)

**Comment by jamonholmgren** [comment]
@dchersey The issue is that Ruby's semantics means you're creating a local var with the name `hidden` rather than setting the property. You'll want to use the `view` reference. Try this:

```ruby
def sign_in_style
    title 'Sign In'
    # other button styling stuff
   always do
        view.hidden=user.signed_in?
   end
end
```

In RMQ, there's a potentially nicer way to do it too:

```ruby
      rmq(@layout.sign_in).get.setHidden(user.signed_in?)
      rmq(@layout.sign_up).get.setHidden(user.signed_in?)
      rmq(@layout.sign_out).get.setHidden(!user.signed_in?)
```

**Comment by jamonholmgren** [comment]
Ha, @colinta, jinx. Your version is nicer.

**Comment by dchersey** [comment]
Thank you both! @colinta's is cleanest syntax, but the view reference from @jamonholmgren is also something I was looking for in the docs. 

Liking :+1: motion-kit more and more!
