### ISSUE TITLE
Helpers to figure out status bar height/navigation bar height?

### ISSUE THREAD

**Issue by dchersey** [motion-kit/motion-kit#133]
I know that the status bar is always either 20 or 40 points (if you are in a call) and also that the navigation bar has a standard height if it's present.  And I'm happy to keep writing code that uses these values ... but it would be nice not to have to worry about it.

I can always calculate these off the statusBarFrame or topLayoutGuide ... but I have to do this on every screen.

Is there something I'm missing in motion-kit that would give me reliable access to these metrics in the layout code, in a nicely abstracted don't-have-to-worry about-it way?  Seems like the frame helpers could let me reference the origin of the visible screen. 

Right now I am using a UIView to contain everything else, and positioning it at 0,20, '100%', '100% - 20pt'
And I need to use one of the above techniques to make sure it's not 40. 

Am I missing an opportunity for elegance here?

**Comment by colinta** [comment]
I assign the UIViewController's `topLayoutGuide` in `viewDidLoad`, that usually does the trick.  If you're relying only on frame code, you can still use the value, just assign it in `viewWillLayoutSubviews`, e.g.

```ruby
def viewWillLayoutSubviews
  super
  layout.top_layout_guide = topLayoutGuide.length
end
```

**Comment by dchersey** [comment]
Thanks!  Sorry to ask a dumb question, but I see that topLayoutGuide is a property of the view controller 
-- is top_layout_guide a property of MotionKit::Layout?  When I try to set it, I get 
```undefined method `top_layout_guide=' for #<MyLayout:0x119f64220>:MyLayout ```

**Comment by colinta** [comment]
No I just made it up, you'll have to add it and respond to it in your layout.

**Comment by dchersey** [comment]
Got it, makes sense.   Still musing on how to handle this transparently in MK.

**Comment by colinta** [comment]
If you come up with something elegant, I'd be interested in including it in motion-kit!

**Comment by dchersey** [comment]
You bet -- will let you know if it comes to fruit.

**Comment by dchersey** [comment]
Just getting back to this -- I'm using ProMotion and am finding it hard to coordinate the setting of the layout guide and the layout of the view.  In ViewDidLoad (or in PM on_load) the topLayoutGuide.length is still 0.  
By the time it gets to viewWillLayoutSubviews it's there. Some logging: 
```
"ON_LOAD: 0.0"
"WILL_APPEAR: 0.0"
"WILL LAYOUT: 64.0"
"DID LAYOUT: 64.0"
"ON_APPEAR: 64.0"
```

ProMotion suggest putting the Layout code in on_load. Not sure if there's a solid reason for this, but it seems to make sense.  So I tried setting `@layout.top_layout_guide = self.topLayoutGuide.length` in viewWillLayoutSubviews then calling `@layout.build` but I found that the layout evaluates its blocks on instantiation (in on_load) so the top_layout_guide is not available.   

So I moved the code that creates the layout and builds it to on_appear (similar to viewDidAppear).  That works, but I'm feeling that's a little late.  I tried putting it in viewWillLayoutSubviews and viewDidLayoutSubviews but both of them created recursive loops. 

```ruby
  def viewDidLayoutSubviews
    mp "DID LAYOUT: #{self.topLayoutGuide.length}"
    super
    @layout = WeLayout.new(root: self.view)
    @layout.on :express {express_feeling true}
    @layout.on :locate {locate_user false}
    @layout.top_layout_guide =  self.topLayoutGuide.length
    @layout.build
    init_map(@layout.map)    
  end
```

So I guess  I'm stuck with on_appear ... or hardcoding the top_layout_guide in on_load. Am I missing something?

**Comment by colinta** [comment]
This should be a two step process:

1. Create the layout in on_load
2. Update the layout when the guide changes

either:
- assign the `topLayoutGuide`, and use the `reapply!` feature of motion-kit to update based on the `length` of that guide or
- assign `topLayoutGuide.length` during `viewWillLayoutSubviews`, and again use `reapply!` to move views based on that value.

Either way, you'll want to animate that change, so that when the user takes a call, the layout adjusts accordingly.

This is kind of an unfortunate "wart" in ios view programming, in my opinion.  It's not really clear how to take the status bar into account, and since it NEVER changes during development (in the simulator), it's easy to forget about. :-/

**Comment by dchersey** [comment]
Ok, this is where I wound up: 

in screen.rb:
```ruby
  def viewWillLayoutSubviews
    if @layout
      @layout.top_layout_guide =  self.topLayoutGuide.length
      @layout.reapply! 
    end
  end
```
in layout.rb:
```ruby
 def topic_filters_style
      ...
    constraints do
      x.equals(:superview)
      @topic_filters_top_constraint = y.equals(:superview).plus(self.top_layout_guide)
      width.equals(:superview)
      height.equals(44)
    end    
    reapply do 
      @topic_filters_top_constraint.equals(self.top_layout_guide)
    end
  end
```

Fortunately I only have 1 subview anchored to the superview.  If I had more, I would enclose all of them in another subview and add this code only once, and anchor all of the others to that subview.

Thinking about how this could be better .... we would ideally have some kind of other anchor for constraints -- instead of :superview it could be :top_layout.  Then there would have to be an update injected from the containing view to the layout.  Is there any existing mechanism for the layout to observe/reference the containing view?  If not, we could default :top_layout to simply equal :superview and provide a method for the programmer to use to update it -- something like mk_synchronize_top_layout.

Maybe this would be easier in mk_2 where the layout IS the view.
