### ISSUE TITLE
Has anyone used MK to layout custom UITableViewCells?

### ISSUE THREAD

**Issue by matthewsinclair** [motion-kit/motion-kit#37]
Quick question: I'm wondering if there's an example anywhere for how to use MK to lay out a custom UITableViewCell?

**Comment by jamonholmgren** [comment]
Just as an update: I've found that using one layout per cell (generally only up to the number you have queued, so not a lot) really works well, especially when combined with a custom cell and ProMotion TableScreens.

```ruby
class MyScreen < PM::TableScreen
  # ...
  def table_data
    [{
      cells: [{
        title: "Whatever",
        properties: {
          sublabel: "sublabel here!",
          sublabel_color: "#F9F9F9",
        }
      }]
    }]
  end
end

class StandardCell < UITableViewCell

  def initWithStyle(style, reuseIdentifier: identifier)
    super
    @layout = StandardCellLayout.new(root: self).build
    self
  end

  def sublabel=(text)
    @layout.sublabel = text
  end

  def sublabel_color=(color)
    @layout.sublabel_color = color
  end
end

class StandardCellLayout < MK::Layout
  def layout
    root :cell do
      context target.textLabel do
        font "Open Sans".uifont(16.0)
      end

      context target.contentView do
        add UILabel do
          constraints do
            # ...
          end
        end
      end
    end
  end

  def sublabel=(text)
    get(:sublabel).text = text
  end

  def sublabel_color=(color)
    get(:sublabel).fontColor = color.uicolor
  end
end
```

**Comment by holgersindbaek** [comment]
There's still no "real" fix for this?

**Comment by jamonholmgren** [comment]
I have a feeling that when we run into it, it'll be a lot higher priority. :) If you can find a fix in the meantime, we'd appreciate the help. Otherwise it could be a bit.

**Comment by holgersindbaek** [comment]
What do you mean "when WE run into it"? I'm already using Matthews temporary fix, but I'm not sure if it's just a temporary fix or one that could be applied as a general one.

**Comment by jamonholmgren** [comment]
I mean that when we at ClearSight run into this issue on one of our apps, we'll invest the time and resources to address the issue permanently. Until then, we have some higher priorities.

**Comment by holgersindbaek** [comment]
@jamonholmgren Arh ok. Didn't know if was a company who where the main guys behind MotionKit.

**Comment by jamonholmgren** [comment]
@holgersindbaek No worries!

Generally, @colinta is the primary developer on MotionKit, but his latest projects have utilized different tech stacks so he's not quite as active as when he's actively using MK.

I'm the secondary contributor to MK (much lower level than Colin) and contribute where I can. I'm pretty busy these days, although it appears that I'll be lightening up my personal workload a bit this summer and can contribute more.

My agency, @clearsightstudio, uses MK on many of our RubyMotion projects, so we contribute patches and improvements as we need them.

**Comment by redhotvengeance** [comment]
I'm running into this same `Invalid Reference - probably recycled (WeakRef::RefError)` issue.

@jamonholmgren I reorganized my code to follow the example you posted above, and I'm still getting this error. Should that example be working? The error pops for me once I start scrolling, and it throws on the equivalent of the `@layout.sublabel = text` line in the `StandardCellLayout`. Any advice for how to work around this issue?

**Comment by jamonholmgren** [comment]
@redhotvengeance It's really two issues conflated in one. The OP is asking what is the best way to handle UITableViewCells in MotionKit, which I think currently stands as what I detailed. The Invalid Reference should be its own issue, and I'd encourage you to make one and reference this issue for back history.

**Comment by silasjmatson** [comment]
I was just able to replicate this issue.

Changing @jamonholmgren's example above to use a pass a `WeakRef` of the cell subclass instance to the layout fixes the crash.

```ruby
class MyScreen < PM::TableScreen
  # ...
  def table_data
    [{
      cells: [{
        title: "Whatever",
        cell_class: StandardCell,
        properties: {
          sublabel: "sublabel here!",
          sublabel_color: "#F9F9F9",
        }
      }]
    }]
  end
end

class StandardCell < UITableViewCell

  def initWithStyle(style, reuseIdentifier: identifier)
    super
    @layout = StandardCellLayout.new(root: WeakRef.new(self)).build
    self
  end

  def sublabel=(text)
    @layout.sublabel = text
  end

  def sublabel_color=(color)
    @layout.sublabel_color = color
  end
end

class StandardCellLayout < MK::Layout
  def layout
    root :cell do
      context target.textLabel do
        font "Open Sans".uifont(16.0)
      end

      context target.contentView do
        add UILabel do
          constraints do
            # ...
          end
        end
      end
    end
  end

  def sublabel=(text)
    get(:sublabel).text = text
  end

  def sublabel_color=(color)
    get(:sublabel).fontColor = color.uicolor
  end
end
```

I don't think it's asking too much to have users pass in a `WeakRef` explicitly, rather than attempting to solve the problem w/in MotionKit.

**Comment by silasjmatson** [comment]
This makes no sense. The circular reference should prevent the deallocation... Maybe RubyMotion detects the circular reference and 'un'-helpfully deallocates?

**Comment by redhotvengeance** [comment]
Switching to a `WeakRef` ala @silasjmatson's example fixes the crash for me as well.

I agree that it is very easy to pass in a `WeakRef` explicitly, although it would be preferable to not have to have an exception just for table view cells, since it would definitely trip up first time MotionKit users (which I am). At the very least, if it can't be fixed in MotionKit, it should be very clearly documented.

**Comment by silasjmatson** [comment]
:+1: For documenting the issue clearly.

**Comment by jamonholmgren** [comment]
I updated my example.

I'll create a markdown doc dealing with table view cells that we can point people to and modify as we figure out best practices. Will do that this weekend, probably.

**Comment by yestoall** [comment]
any news about this example form TableViewCell with ProMotion and MotionKit? :)

**Comment by jamonholmgren** [comment]
Hm, I think I made that gist, but I can't find it!

I've been using a new layout instance for every cell.
