### ISSUE TITLE
Terminating app due to uncaught exception 'WeakRef::RefError' with ProMotion

### ISSUE THREAD

**Issue by visoft** [motion-kit/motion-kit#56]
Using ProMotion 2.0.0.rc4 + motion-kit 0.10.8, I get the error `Terminating app due to uncaught exception 'WeakRef::RefError', reason: 'Invalid Reference - probably recycled (WeakRef::RefError)` when navigating between screens. I stripped out the motion-kit code and the error doesn't happen, thus I figure it must be a problem within motion-kit.

See https://github.com/visoft/chat_test for the problem.

**Comment by divmgl** [comment]
Was this ever completely solved? I'm getting a WeakRef issue when storing a constraint

**Comment by colinta** [comment]
I haven’t heard of a WeakRef issue in a long time, I thought we got em all.  And def the first time I heard about it in reference to a constraint.
