### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by andrewhr** [motion-kit/motion-kit#92]
The README manifest interest in supporting Android too, since RubyMotion was announced. There is any plan to how to accomplish that?

This library seems very coupled to UI code on iOS and OS X - not only internally but in the way it is used. A **Good Thing™** IMO. I wonder that, to support Android, there is two possible strategies to adopt.

The first one is put more abstraction on top of `motion-kit` DSL and deal with multi-platform concerns internally. This will bring a kind of _write-once_ style, but will push a lot of complexity inside the library. Also we could end with scenario of minimum viable capabilities since both devices will need to support the whole DSL.

A second one is  keeping this library focused on Apple and make another one just for Android. The libraries will be both very focused, but the burden of writing the final interface will be on the developers using `motion-kit`. I pretty like this approach, because in the end the developers could use the whole power of the target platform. Anyway, a `core` kind of gem could keep a common interface, so the DSL will not diverge entirely, but instead just narrow to the target.

If something like that (or any other strategy) is of interest of the `motion-kit` I could help in any way I can.

Thanks for the attention spend.

**Comment by zmillman** [comment]
Colin's slide 28 here makes it look like there is already some kind of support for Android: http://www.slideshare.net/colinta/kill-the-controllers-and-an-introduction-to-motionkit

Is that some kind of internal fork?

**Comment by jamonholmgren** [comment]
Well, as you can see, he doesn't always keep me in the loop:

![screen shot 2015-02-12 at 6 51 37 pm](https://cloud.githubusercontent.com/assets/1479215/6181471/3af7494e-b2e8-11e4-8df8-bd85e9c86734.png)

;-)

Just kidding...he had to keep it under wraps because RM-Android wasn't public yet.

**Comment by zmillman** [comment]
Touché :smile: 

Well, if Colin does decide to merge it in, I'd be happy to help. I'm working on porting a RubyMotion iOS app to Android so it would be great to use the same libraries in both apps.

**Comment by colinta** [comment]
I'll merge what I've got, but it's dated and was based on "hopeful" (thoroughly untested) code.

**Comment by zmillman** [comment]
Ah, maybe a PR then to test it without interfering with a stable master?

On Thu, Feb 12, 2015 at 7:13 PM, Colin T.A. Gray <notifications@github.com>
wrote:

> I'll merge what I've got, but it's dated and was based on "hopeful"
> (thoroughly untested) code.
>
>
>
> > On Feb 12, 2015, at 8:02 PM, Zach Millman <notifications@github.com>
> wrote:
> >
> > Touché
> >
> > Well, if Colin does decide to merge it in, I'd be happy to help. I'm
> working on porting a RubyMotion iOS app to Android so it would be great to
> use the same libraries in both apps.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motion-kit/motion-kit/issues/92#issuecomment-74198482>
> .
>



-- 
Zach Millman

(415)-515-4770
